import { TemplateDescriptor } from "../../domain/models/TemplateDescriptor";

export const nextJsFullstack: TemplateDescriptor = {
  id: "nextjs-fullstack",
  name: "Next.js Fullstack (App Router, TS)",
  category: "web",
  folders: [
    "app",
    "app/api",
    "app/components",
    "public"
  ],
  files: [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "nextjs-fullstack",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
          },
          dependencies: {
            next: "14.2.0",
            react: "^18.3.0",
            "react-dom": "^18.3.0"
          },
          devDependencies: {
            typescript: "^5.4.0",
            "@types/react": "^18.3.0",
            "@types/react-dom": "^18.3.0",
            eslint: "^9.0.0"
          }
        },
        null,
        2
      )
    },
    {
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2020",
            module: "ESNext",
            jsx: "preserve",
            moduleResolution: "bundler",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
          exclude: ["node_modules"]
        },
        null,
        2
      )
    },
    {
      path: "next.config.mjs",
      content: `/** @type {import("next").NextConfig} */
const nextConfig = {
  reactStrictMode: true
};

export default nextConfig;
`
    },
    {
      path: "app/layout.tsx",
      content: `import React from "react";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
    },
    {
      path: "app/page.tsx",
      content: `export default function Page() {
  return (
    <main style={{ padding: 24 }}>
      <h1>ProjectForge Next.js Fullstack</h1>
      <p>Generated by ProjectForge.</p>
    </main>
  );
}
`
    },
    {
      path: "app/api/hello/route.ts",
      content: `import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({ message: "Hello from ProjectForge API" });
}
`
    }
  ]
};
