import { TemplateDescriptor } from "../../domain/models/TemplateDescriptor";

export const reactTsAdvanced: TemplateDescriptor = {
  id: "react-ts-advanced",
  name: "React TypeScript Advanced (Vite)",
  category: "web",
  folders: [
    "src",
    "src/components",
    "src/hooks",
    "src/styles",
    "public"
  ],
  files: [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "react-ts-advanced",
          private: true,
          scripts: {
            dev: "vite",
            build: "vite build",
            preview: "vite preview",
            lint: "eslint src --ext .ts,.tsx"
          },
          dependencies: {
            react: "^18.3.0",
            "react-dom": "^18.3.0"
          },
          devDependencies: {
            typescript: "^5.4.0",
            vite: "^5.0.0",
            "@vitejs/plugin-react-swc": "^4.0.0",
            "@types/react": "^18.3.0",
            "@types/react-dom": "^18.3.0",
            eslint: "^9.0.0"
          }
        },
        null,
        2
      )
    },
    {
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2020",
            module: "ESNext",
            jsx: "react-jsx",
            moduleResolution: "bundler",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true
          },
          include: ["src"]
        },
        null,
        2
      )
    },
    {
      path: "vite.config.ts",
      content: `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173
  }
});
`
    },
    {
      path: "index.html",
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>React TS Advanced</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
    },
    {
      path: "src/main.tsx",
      content: `import React from "react";
import ReactDOM from "react-dom/client";
import { App } from "./App";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`
    },
    {
      path: "src/App.tsx",
      content: `import React from "react";

export const App: React.FC = () => {
  return (
    <div style={{ padding: 24 }}>
      <h1>ProjectForge React TS Advanced</h1>
      <p>Generated by ProjectForge.</p>
    </div>
  );
};
`
    },
    {
      path: ".eslintrc.json",
      content: JSON.stringify(
        {
          env: { browser: true, es2020: true },
          extends: ["eslint:recommended", "plugin:react/recommended"],
          parserOptions: { ecmaVersion: 2020, sourceType: "module" },
          settings: { react: { version: "18.0" } }
        },
        null,
        2
      )
    }
  ]
};
