import { TemplateDescriptor } from "../../domain/models/TemplateDescriptor";

export const vanillaHtmlCssJs: TemplateDescriptor = {
  id: "vanilla-html-css-js",
  name: "Vanilla HTML/CSS/JS",
  category: "web",
  folders: ["src", "src/assets"],
  files: [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "vanilla-html-css-js",
          private: true,
          scripts: {
            dev: "live-server src",
            build: "echo \"No build step for vanilla\""
          },
          devDependencies: {
            "live-server": "^1.2.2"
          }
        },
        null,
        2
      )
    },
    {
      path: "src/index.html",
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Vanilla ProjectForge</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <h1>ProjectForge Vanilla HTML/CSS/JS</h1>
    <p>Generated by ProjectForge.</p>
    <script src="./main.js"></script>
  </body>
</html>
`
    },
    {
      path: "src/styles.css",
      content: `body {
  font-family: system-ui, sans-serif;
  padding: 24px;
}
`
    },
    {
      path: "src/main.js",
      content: `console.log("ProjectForge vanilla project ready.");`
    }
  ]
};
