import { TemplateDescriptor } from "../../domain/models/TemplateDescriptor";

export const electronReact: TemplateDescriptor = {
  id: "electron-react",
  name: "Electron + React (TypeScript)",
  category: "desktop",
  folders: ["src", "src/main", "src/renderer"],
  files: [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "electron-react",
          private: true,
          main: "dist/main/main.js",
          scripts: {
            dev: "concurrently \"npm:dev:main\" \"npm:dev:renderer\"",
            "dev:main": "ts-node-dev --respawn --transpile-only src/main/main.ts",
            "dev:renderer": "vite",
            build: "npm run build:main && npm run build:renderer",
            "build:main": "tsc -p tsconfig.main.json",
            "build:renderer": "vite build"
          },
          dependencies: {
            electron: "^30.0.0",
            react: "^18.3.0",
            "react-dom": "^18.3.0"
          },
          devDependencies: {
            typescript: "^5.4.0",
            "ts-node-dev": "^2.0.0",
            "@vitejs/plugin-react-swc": "^4.0.0",
            vite: "^5.0.0",
            concurrently: "^8.0.0"
          }
        },
        null,
        2
      )
    },
    {
      path: "tsconfig.main.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2020",
            module: "commonjs",
            strict: true,
            esModuleInterop: true,
            outDir: "dist/main",
            rootDir: "src/main"
          },
          include: ["src/main"]
        },
        null,
        2
      )
    },
    {
      path: "tsconfig.renderer.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2020",
            module: "ESNext",
            jsx: "react-jsx",
            strict: true,
            esModuleInterop: true
          },
          include: ["src/renderer"]
        },
        null,
        2
      )
    },
    {
      path: "vite.config.ts",
      content: `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";

export default defineConfig({
  plugins: [react()],
  root: "src/renderer",
  build: {
    outDir: "../../dist/renderer"
  }
});
`
    },
    {
      path: "src/main/main.ts",
      content: `import { app, BrowserWindow } from "electron";
import * as path from "node:path";

function createWindow() {
  const win = new BrowserWindow({
    width: 1024,
    height: 768
  });

  win.loadFile(path.join(__dirname, "../renderer/index.html"));
}

app.whenReady().then(createWindow);
`
    },
    {
      path: "src/renderer/index.html",
      content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>ProjectForge Electron React</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./main.tsx"></script>
  </body>
</html>
`
    },
    {
      path: "src/renderer/main.tsx",
      content: `import React from "react";
      import ReactDOM from "react-dom/client";
      
      const App = () => (
        <div style={{ padding: 24 }}>
          <h1>ProjectForge Electron + React</h1>
          <p>Generated by ProjectForge.</p>
        </div>
      );
      
      ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
        <React.StrictMode>
          <App />
        </React.StrictMode>
      );
`
    }
  ]
};
