import { TemplateDescriptor } from "../../domain/models/TemplateDescriptor";

export const tauriRustReact: TemplateDescriptor = {
  id: "tauri-rust-react",
  name: "Tauri + Rust + React",
  category: "desktop",
  folders: ["src", "src-tauri"],
  files: [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "tauri-rust-react",
          private: true,
          scripts: {
            dev: "tauri dev",
            build: "tauri build"
          },
          devDependencies: {
            "@tauri-apps/cli": "^2.0.0",
            react: "^18.3.0",
            "react-dom": "^18.3.0",
            vite: "^5.0.0",
            "@vitejs/plugin-react-swc": "^4.0.0",
            typescript: "^5.4.0"
          }
        },
        null,
        2
      )
    },
    {
      path: "src/main.tsx",
      content: `import React from "react";
import ReactDOM from "react-dom/client";

const App = () => (
  <div style={{ padding: 24 }}>
    <h1>ProjectForge Tauri + React</h1>
    <p>Generated by ProjectForge.</p>
  </div>
);

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`
    },
    {
      path: "src-tauri/Cargo.toml",
      content: `[package]
name = "projectforge_tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0.0", features = ["shell-open"] }
`
    },
    {
      path: "src-tauri/src/main.rs",
      content: `fn main() {
  tauri::Builder::default()
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
`
    }
  ]
};
