import { TemplateDescriptor } from "../../domain/models/TemplateDescriptor";

export const vscodeExtensionTsTemplate: TemplateDescriptor = {
  id: "vscode-extension-ts-template",
  name: "VS Code Extension (TypeScript)",
  category: "extension",
  folders: ["src"],
  files: [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          name: "sample-vscode-extension",
          displayName: "Sample VS Code Extension",
          description: "Generated by ProjectForge.",
          version: "0.0.1",
          publisher: "your-name",
          engines: { vscode: "^1.90.0" },
          main: "./out/extension.js",
          activationEvents: ["onCommand:sample.helloWorld"],
          contributes: {
            commands: [
              {
                command: "sample.helloWorld",
                title: "Sample: Hello World"
              }
            ]
          },
          scripts: {
            build: "tsc -p tsconfig.json",
            watch: "tsc -w -p tsconfig.json"
          },
          devDependencies: {
            typescript: "^5.4.0",
            "@types/node": "^20.0.0",
            "@types/vscode": "^1.90.0"
          }
        },
        null,
        2
      )
    },
    {
      path: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2020",
            module: "commonjs",
            strict: true,
            esModuleInterop: true,
            outDir: "out",
            rootDir: "src"
          },
          include: ["src"]
        },
        null,
        2
      )
    },
    {
      path: "src/extension.ts",
      content: `import * as vscode from "vscode";

export function activate(context: vscode.ExtensionContext) {
  const disposable = vscode.commands.registerCommand("sample.helloWorld", () => {
    vscode.window.showInformationMessage("Hello World from ProjectForge template!");
  });

  context.subscriptions.push(disposable);
}

export function deactivate() {}
`
    }
  ]
};
